# Generated by Django 4.0.4 on 2022-06-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Вік')),
                ('hematocrit', models.FloatField(default=0, verbose_name='Гематокрит')),
                ('red_blood_cells', models.FloatField(default=0, verbose_name='Еритроцити')),
                ('lymphocytes', models.FloatField(default=0, verbose_name='Лімфоцити')),
                ('leukocytes', models.FloatField(default=0, verbose_name='Лейкоцити')),
                ('basophils', models.FloatField(default=0, verbose_name='Базофіли')),
                ('eosinophils', models.FloatField(default=0, verbose_name='Еозинофіли')),
                ('monocytes', models.FloatField(default=0, verbose_name='Моноцити')),
                ('glucose', models.FloatField(default=0, verbose_name='Глюкоза')),
                ('neutrophils', models.FloatField(default=0, verbose_name='Нейтрофіли')),
                ('c_reactive_protein', models.FloatField(default=0, verbose_name='С-реактивний білок')),
                ('creatinine', models.FloatField(default=0, verbose_name='Креатинін')),
                ('potassium', models.FloatField(default=0, verbose_name='Калій')),
                ('sodium', models.FloatField(default=0, verbose_name='Натрій')),
                ('alat', models.FloatField(default=0, verbose_name='АЛАТ (Аланінамінотрансфераза)')),
                ('asat', models.FloatField(default=0, verbose_name='АСАТ (Аспартатамінотрансфераза)')),
                ('bilirubine', models.FloatField(default=0, verbose_name='Білірубін')),
            ],
            options={
                'verbose_name': 'Аналіз крові',
                'verbose_name_plural': 'Аналізи крові',
                'ordering': ['age'],
            },
        ),
    ]
